name: Django CI/CD
on:
  push:
    branches:
      - main
      - staging
      - dev
jobs:
  build:
    runs-on: ubuntu 20.04
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  

    - name: Install dependencies
      run: 
        pip install -r requirements.txt 
    
    - name: Make migrations
      run: 
        python manage.py migrate

    - name: Run tests
      run: 
        python manage.py test
    
    - name: Install Pre-commit
      run:
        pip install pre-commit
    
    - name: Run Pre-commit
      run: 
        pre-commit run --all-files